CONTRIBUTING.md
README.md

do you like? my revision?
- neat
- orderly
- good looking
:clinking_glasses:

do you like? my revision?

---

README.md

re-add:
- Polymer Indonesia
- Raspberry PI Indonesia
- Electron Desktop User Group
- Frontend Developer Indonesia
- Big Data Indonesia
- Kongkow IT Medan

Re-add missing groups

---

README.md

more info about DOSCOM you can checkout doscom.org
and TeaLinuxOS at tealinuxos.org
Thanks!

 add DOSCOM - Dinus Open Source Community & TeaLinuxOS :tada:

---

README.md

Added Xamarin Indonesia group. 
DONE.

#12 - Added Xamarin Indonesia group

---

README.md

- add react indonesia group.
- sort javascript group alphabetically.

Add React ID group

---

README.md

change Big Data to Data PlayGround
add t.me/ScrapeID

add @ScrapeID

---

README.md

Salam mas,
Ini ada grup diskusi C/C++. Saat ini sudah 114 member. Mohon di add di listnya.

Add C/C++ section and add Indonesia C/C++ Warriors group

---

README.md

Linux Mint Indonesia

---

README.md

Menambahkan grup Windows

---

README.md

- Menambahkan Grup Slackware Indonesia dan Emacs

Menambahkan Emacs Group Indonesia

---

.gitignore
.travis.yml
CONTRIBUTING.md
README.md
spec/readme_spec.cr
util/readme.cr
util/stats.cr

+ talk about test driven development, &etc

add TDD, add some group, remove dead link

---

README.md

* tentang telegram
* telegram beta
* telegram themes

menambahkan grup tentang telegram

---

README.md

Hai mas @hendisantika ijin add Haskell group ya.. Trims

Adding Haskell

---

README.md

Pak Hendi, berikut adalah 3 grup tambahan yang jumlah anggotanya cukup banyak dan kayaknya bisa dimasukkan ke awesome list

Add Rust Indonesia, C# Indonesia, and Machine Learning Indonesia

---

README.md

add link telegram for ISQA group.

add ISQA Telegram group

---

README.md

halo mas hendi, saat ini member cirebonDev sudah mencapai 100orang lebih, saya izin PR lagi, supaya grup ini makin dikenal, terutama orang orang cirebon sendiri yg belum tau keberadaan grup ini 😃 , thank you

enhance cirebonDev in list

---

README.md

+ Fix some links group 
+ add SQL Server group

update link and add group

---

README.md

minimum member 100 people reached

add block chain indonesia

---

README.md

- [Telegram Bot PHP - Indonesia](https://t.me/botphp) => Grup diskusi develop bot telegram dengan PHP
- [Arduino Indonesian Community](https://t.me/ArduinoIndonesianCommunity)
- [Arch Linux Indonesia](https://t.me/ArchLinuxID)
- [CentOS.ID](https://t.me/centosID)
- [Deepin Linux Indonesia](https://t.me/deepin_indonesia)
- [Manjaro Indonesia](https://t.me/manjaroID)
- [openSUSE Indonesia](https://t.me/openSUSE_ID)
- [ParrotSec Indonesia](https://t.me/parrotsecurityindonesia)
- [Ubuntu Indonesia](https://t.me/ubuntu_id)
- [WINDOWS SERVER INDONESIA](https://t.me/WindServID)
- [Javascript Indonesia](https://t.me/js_id)

Tambah beberapa link grup

---

README.md

Maaf bikin PR baru. PR kemarin ada kesalahan saat resolve conflict.

add [programmer semarang raya,  Semarang JS]

---

README.md

penambahan grup trading bitcoin

grup bitcoin

---

README.md

This is basic rules of capitalization https://en.wikipedia.org/wiki/Capitalization

Use capital letter at beginning of country name

---

README.md

Added Lombok js, Lombok.py, and Lombok Android Developer groups

Add more groups

---

README.md

Menambah Grouplist BSD + Link group Laskar Setan Merah

Tambah Grouplist BSD

---

README.md

tambah link grup telegram untuk komunitas GNU/ Linux area Malang dan sekitarnya

add link group Komunitas GNU/Linux Malang(KLiM)

---

README.md

Informasi Lowongan Pekerjaan Ruby dan Ruby on Rails Indonesia

Tambah Channel Ruby dan Rails Indonesia Loker

---

README.md

a javasript community based on Batam

add coderjs group

---

README.md

Add Android Developer Medan telegram group

Add Android Developer Medan telegram group

---

README.md

grub belajar bikin bot telegram

add grup baru

---

README.md

Mohon maaf yang sebelumnya anggotanya kurang dari 100, saat ini sudah 100 lebih pak Hendi.
Terima kasih

Add SurabayaJs telegram group

---

README.md

Halo kang Hendi, saya Ihwan mohon izin menambahkan Kotlin Cirebon User Group. Terimakasih

add Kotlin Cirebon

---

README.md
_config.yml

Close https://github.com/hendisantika/List-All-Programming-Telegram-Group/issues/90

GitHub pages and group reorders

---

README.md

Add NativeScript ID

---

README.md

Add development telegram community for my own city Jember called Djember Dev

Add Djember Dev Community

---

README.md

Group untuk berdiskusi seputar teknologi & tools Business Intelligence (BI) seperti : 
- Tableau
- Ms PowerBI
- Tibco Spotfire
- Qlikview
- Microstrategy
- YellowFin
- Domo
- Opensource BI (Superset, Redash, Metabase etc) 
- DLL

Added Business Intelligence Indonesia Group

---

README.md

add mks.py community of python developers at Makassar and Sulawesi area

Update README.md section Python

---

README.md

**BogorDev** is a community of Developers at Bogor
Github : [Bogor Developers](https://github.com/Bogor-Developers)

Modified README.md for Bogor Developers Group

---

README.md

Halo bung,
Saya lihat **Laravel Semarang** belum ada, dan grup sudah memenuhi kriteria dari `CONTRIBUTING.md`

add laravel semarang

---

README.md

Add **dart.web** telegram group, discussion for web programming with Dart

Update README.md section Dart

---

README.md

Adding new telegram group about Natural Language in Indonesia

adding group  Natural Language ID

---

README.md

Saya coba menambahkan PasuruanDev di list development.
Terima kasih

Update README.md, add pasuruandev in list of link development community

---

README.md

In my opinion, AIDI is a part of programming environment

Adding AIDI (Asosiasi ilmuwan Data Indonesia)

---

README.md

Add ISQA Jogja Telegram Group #DevCJog25

---

README.md

- Paguyuban Linux Solo
- Komunitas Linux Jember

add group linux

---

README.md

Selamat malam om @hendisantika 
Izin nambahin grup telegram buat Svelte 
Makasih

added Svelte Indonesia

---

README.md

Izin nambahin lagi om @hendisantika 
Makasih

added Jakarta JavaScript User Group

---

README.md

Selamat malam Pak @hendisantika,
Mohon izin menambahkan beberapa komunitas di kota malang:
- [Malang Quality Assurace](https://t.me/qamalang)
- [Kelas Mobile Malang](https://t.me/KelasMobileMalang)
- [Ngalam Backend Community (NBC Malang)](https://kutt.it/nbcTelegramGroup)
- [Malang Hacker Link](https://t.me/joinchat/DCdoGFc4IY0p06rQfoVtcQ)
Terima kasih.

Add some communities in Malang City

---

README.md

Add Friends with Blockchain(FWB) in Blockchain Section

add new blockchain group

---

README.md

A secure runtime for JavaScript and TypeScript built with V8, Rust, and Tokio

Add Deno JS Indonesia

---

README.md

Propose for Leaflet.js Indonesia

Propose for Leaflet.js Indonesia

---

README.md

please review this addition @hendisantika

add Tailwind Indonesia, Software Engineer Indonesia and Flutter Jakarta

---

README.md

Developer Muda Unity
Freelance Project IT
Loker Jakarta
Source Code Android
Startup Weekend Indonesia

 Add Freelance, startup, gamedev, loker

---

README.md

add group typescript Indonesia

add typescript group

---

README.md

Hi, I've added the Kotakode telegram channel in the Readme.Md

added kotakode

---

README.md

Add SARCCOM Universe

---

README.md

Add new PHPID telegram group link.

Add PHPID for Business

---

README.md

saya telah menambahkan grub "Komunitas Belajar Koding" di list Development.

add group komunitas belajar koding

---

README.md

Add AWS Analytics User Group Indonesia

Add AWS Analytics User Group Indonesia

---

README.md

- Adding 'Komunitas Backend Developer'
- Adding 'TensorFlow Indonesia'
- Remove bigdataID & Komunitas Programmer Makassar  because of inactive links
- Reorder 'Data Playground' section

Adding 2 groups, remove inactive link (Komunitas Programmer Makassar & Big Data Indonesia), and reorder a section

---

README.md

Add Lombok Games Developers (LGD)

---

README.md

Add PyTorch Indonesia: Group untuk diskusi dan sharing Deep Learning Framework PyTorch di regional Indonesia.
adjust the list of Data Playground in alphabetical order, as guided in contributing.md.

Add PyTorch Indonesia & adjust alphabetical order

---

README.md

Hi Team, I'm the community lead of the [Kulkul.tech](https://kulkul.tech/)'s community. I'm willing to have my community included in this list as the community is already met the requirements of having more than 100 members.

Add Kulkul.tech community

---

README.md

Fixing typo on Bootstrap group name and category.

Fixing typo on Bootstrap

---

README.md

hanya menambahkan satu grup : Lombok Flutter

add Lombok Flutter

---

README.md

Perubahan:
- Menghapus broken links yang disebutkan di issue #211 (sudah dicek)
- [Android Developer Medan](https://t.me/android_dev_medan)
- [C# Indonesia](https://t.me/idcsharp)
- [Laravel Semarang](https://t.me/LaravelSemarang)
- [ServerLess Tech](https://t.me/ServerlessTech)
- Menambahkan [GCP User Group Indonesia](https://t.me/GCPUserID)

Remove broken links (#211) and add GCP User Group

---

README.md

Add Hyperledger (Enterprise) Blockchain Indonesia Group.

Add Hyperledger Indonesia

---

README.md

- **.NET** sekarang sudah jadi foundation. jadi lebih cocok dikeluarin dari section **Microsoft**
- Microsoft SQL Server saya pindah ke bawah ke bagian **DATABASE**

Split Microsoft section

---

README.md

Hi Pak, Mohon ditambahkan group azure id.
Terima Kasih.

Adding Azure ID Group

---

README.md

Dear, Maintainer
Izin menambahkan paguyuban pengembang bernama : Teknologi Umum.
Paguyuban tersebut berisi diskusi terkait teknologi dan pengembangan perangkat lunak secara umum.
Terima Kasih.

Menambahkan Paguyuban Teknologi Umum

---

README.md

Dear, Maintainer.
Izin menambahkan paguyuban terkait game development yaitu Paguyuaban Indonesian GDevelop.
GDevelop adalah game engine 2D dengan pendekatan no-code.
Terima kash.

Menambahkan Paguyuban GDevelop Indonesia

---

README.md

Menambahkan grup: 
- Flutter Semarang
- Game dev Semarang
- Nusantara chain (blockchain)
- OSINT Indonesia

Menambahkan beberapa grup 

---

README.md

Kindly add [**Next.js Indonesia**](https://t.me/nextjs_id) group, sir. Thank you.

Add Next.js Indonesia

---

README.md

This link of group 
https://t.me/cScript

add group [c]oretan Script

---

README.md

Please Add GatsbyJS Indonesia to the list. 
Thank You
b,regards,
ariefs

Add GatsbyJS Indonesia

---

README.md

I have recheck some of invite link and found if they are invalid or has expired.

Remove invalid invite link

---

README.md

Add Python BR Group

---

README.md

Add new categories and openstack indonesia group

---

README.md

The Borneo Coding Community includes mobile, web, and linux developers.

add Borneo Coding Community

---

README.md

Roacode was changed invitation links

modified Roacode Link

---

README.md

Added group link for Komunitas RPA Indonesia #263

feat: add RPA group

---

README.md

update reactjs id

---

README.md

update link yang sudah gk bisa dan grub yang ganti account serta tambahan grub semoga membantu, mohon di check jika ada kesalahan, Terima kasih

update link telegram grup

---

README.md

adding 
```
- [OKD Indonesia](https://t.me/okdindonesia)
```

adding OKD Indonesia on DevOps segment

---

CONTRIBUTING.md
README.md

In this PRs consist of the following:

Refactor to encourage user-friendly for mobile browser

---

README.md

In the CONTRIBUTING.md not stated about local only telegram group.
So I add mongoDB English group

add internatioanl mongoDB group

---

README.md

Menambahkan forum HackTheBox Indonesia. Forum terbuka untuk belajar Cyber Security, Pentesting, Ethical Hacking, dan CTF dengan platform HackTheBox.

add HackTheBox Indonesia

---

README.md

Menambahkan link telegram dari komunitas Ceph.id

add Ceph.id telegram group

---

README.md

Migrasi dari grup lama ke grup baru yang aktif

Update Golang Indonesia

---

README.md

Halo mas @hendisantika salam kenal!
Izin menambahkan group terbaru yaa di development.

docs: menambahkan group terbaru di development

---

README.md

Izin menambahkan informasi grup telegram Rust Indonesia pada section Programming Language

Docs : Menambahkan Grup Telegram Rust di Programming Language

---

README.md

mas tolong di check dulu sebelum di merge :
1. check apakah itu channel atau grub, jadi bedakan
2. check itu grub aktif atau bukan atau isi nya orang inggris gk jelas, spammer, dll
3. liat percakapan nya apakah update atau tidak atau hanya sekedar posting job ( kalau postingan job bukan grub itu namanya jadi hapus aja)
liat lagi tujuan mas bikin repository nya, jangan sampai ini dimanfaat kan oleh spammer, org gk jelas, yg nanti semua grub indonesia di manfaatkan mereka, jadi ladang kita nanti, kalau grub aktif ok kalau dead ya delete, kalau mereka mau gabung ok tapi paham aturannya jangan hanya merusuh yang ujung2 nya di block bot di setiap grub

hapus grub rust electron dan jakarta js

---

README.md

Saya menambahkan Telegram Group GNU Emacs Indonesia

Emacs Indonesia

---

README.md

mas ini bun sedang popular trus ada yang bikin grub nya tapi masih dikit dan kayak nya lumayan aktif, member sana minta masukin ke list ini biar makin rame, terima kasih mas

add group bun indonesia

---

README.md

Added Rust Indonesia and DevOps jogja telegram groups. Please review 🙏

feat: add rust id and jogjajs telegram groups

---

README.md

Menambahkan Telegram Group NixOS Indonesia

NixOS Indonesia

---

README.md

- Add BandungDev in Development section
- Move coretanscript below codingfess

Add BandungDev
